-- Intuition:
-- The problem asks us to find stadium visits that have at least 100 people for three or more consecutive days.
-- This means we need to identify sequences of days where the 'people' count is 100 or more, and these sequences must be at least three days long.

-- Approach:
-- 1. Filter the 'stadium' table to include only days where the 'people' count is 100 or more.
-- 2. To identify consecutive days, the current solution uses a series of OR conditions with subqueries checking for adjacent days (id-1, id-2, id+1, id+2) that also meet the 'people >= 100' criteria.
--    - The first condition `(a.id - 1 IN (...) AND a.id + 1 IN (...))` checks if the current day is the middle day of a 3-day sequence.
--    - The second condition `(a.id - 1 IN (...) AND a.id - 2 IN (...))` checks if the current day is the last day of a 3-day sequence.
--    - The third condition `(a.id + 1 IN (...) AND a.id + 2 IN (...))` checks if the current day is the first day of a 3-day sequence.
-- 3. Use `DISTINCT` to ensure that each qualifying day is listed only once, even if it's part of multiple consecutive sequences.
-- 4. Order the final result by `id` for a clear, chronological output.

-- Time Complexity:
-- The current solution involves multiple subqueries and `IN` clauses. In the worst case, each subquery might scan the `stadium` table.
-- If `N` is the number of rows in the `stadium` table, the complexity could be O(N^2) in the worst case, depending on the database optimizer and indexing.
-- A more optimized approach using window functions (e.g., `LAG`, `LEAD`, or `ROW_NUMBER` to identify consecutive groups) would typically achieve O(N log N) due to sorting for window functions, or O(N) with proper indexing.

-- Space Complexity:
-- The space complexity depends on the intermediate results generated by the subqueries and the size of the filtered data.
-- In the worst case, if many rows satisfy the `people >= 100` condition, the subqueries could generate temporary tables proportional to N, leading to O(N) space complexity.

SELECT DISTINCT a.id, a.visit_date, a.people
FROM stadium a
WHERE a.people >= 100
AND (
    (a.id - 1 IN (SELECT id FROM stadium WHERE people >= 100) 
     AND a.id + 1 IN (SELECT id FROM stadium WHERE people >= 100))
    OR
    (a.id - 1 IN (SELECT id FROM stadium WHERE people >= 100) 
     AND a.id - 2 IN (SELECT id FROM stadium WHERE people >= 100))
    OR
    (a.id + 1 IN (SELECT id FROM stadium WHERE people >= 100) 
     AND a.id + 2 IN (SELECT id FROM stadium WHERE people >= 100))
)
ORDER BY a.id;