-- Intuition:
-- The problem asks us to calculate the total of all `tiv_2016` values for insurance policies that meet two specific criteria:
-- 1. The `tiv_2015` value must be shared by at least one other policy (i.e., not unique).
-- 2. The `(lat, lon)` coordinates must be unique for that policy (i.e., no other policy has the same location).

-- Approach:
-- 1. Identify policies with non-unique `tiv_2015`:
--    - Use a subquery to find all `tiv_2015` values that appear more than once in the `Insurance` table.
--    - The main query will filter policies where `tiv_2015` is in this set.
-- 2. Identify policies with unique `(lat, lon)` coordinates:
--    - Use another subquery to find all `(lat, lon)` pairs that appear exactly once in the `Insurance` table.
--    - The main query will further filter policies where `(lat, lon)` is in this set.
-- 3. Combine these conditions:
--    - The `WHERE` clause in the main query will use `AND` to ensure both conditions are met.
-- 4. Calculate the sum of `tiv_2016`:
--    - Use `SUM(tiv_2016)` on the filtered policies.
-- 5. Round the result:
--    - Use `ROUND(..., 2)` to format the sum to two decimal places.

-- Time Complexity:
-- The time complexity will be dominated by the subqueries, each involving a scan and a `GROUP BY` operation on the `Insurance` table.
-- If `N` is the number of policies in the `Insurance` table:
-- - Each subquery with `GROUP BY` and `HAVING` will typically take O(N log N) due to sorting for grouping, or O(N) if hashing is used and well-distributed.
-- - The main query then filters based on the results of these subqueries.
-- - Overall, the time complexity is approximately O(N log N) in the worst case, or O(N) with optimal indexing and query planning.

-- Space Complexity:
-- The space complexity depends on the intermediate results generated by the subqueries.
-- - Each subquery might require O(N) space to store the grouped results.
-- - Overall, the space complexity is approximately O(N) for storing intermediate results.

SELECT 
    ROUND(SUM(tiv_2016), 2) AS tiv_2016
FROM Insurance
WHERE tiv_2015 IN (
    SELECT tiv_2015
    FROM Insurance
    GROUP BY tiv_2015
    HAVING COUNT(*) > 1
)
AND (lat, lon) IN (
    SELECT lat, lon
    FROM Insurance
    GROUP BY lat, lon
    HAVING COUNT(*) = 1
)